### ISSUE TITLE
A-site displacement file

### ISSUE THREAD

**Issue by B209678-2021** [riboviz/example-datasets#110]
We are generating yaml files for the Sharma et al., (2021) dataset for both S. pombe and C. Albicans. 

We are wondering if we should specify an asite_disp_length_file?

fungi/candida/Muzzey_2014_RPF_3-samples_CDS_with_120utrs_config.yaml specifies asite_disp_length_file: null

fungi/candida/Mundodi_2021_RPF_37C_CDS_with_120utrs_config.yaml specifies asite_disp_length_file: data/yeast_standard_asite_disp_length.txt

fungi/schizosaccharomyces/Rubio_2020_stress_config.yaml has asite_disp_length_file: null

@ewallace @ewallace Do you know if we should specify this file for S. pombe and C. Albicans.

**Comment by acope3** [comment]
For now, I would use the `data/yeast_standard_asite_disp_length.txt`, which usually works okay for eukaryotes. We can always try different A-site offsets post-hoc.
