### ISSUE TITLE
Add Weinberg & Shah 2016 Saccharomyces cerevisiae dataset

### ISSUE THREAD

**Issue by FlicAnderson** [riboviz/example-datasets#20]
Add the Weinberg & Shah 2016 dataset to example-datasets (via riboviz/#29)

Weinberg & Shah 2016 dataset is: **Improved Ribosome-Footprint and mRNA Measurements Provide Insights into Dynamics and Regulation of Yeast Translation.**

[Link to paper](https://www.ncbi.nlm.nih.gov/pubmed/26876183)
[Link to RNA-seq reads, GSE75897](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE75897)
[Link to Ribosome-Protected Fragment reads, GSM1289257](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1289257)
Note: links edited by @ewallace , 5th Feb 2021)

**Comment by ewallace** [comment]
Discussed 11th Jan 2021, assigned to @3mma-mack and @swinterbourne as their first riboviz task for their honours project. This can be done as part of the hackathon.

**Comment by FlicAnderson** [comment]
Just a note for @3mma-mack and @swinterbourne about "adding" this dataset to the example-datasets repository: 

Since we've already got annotation files for *S. cerevisiae* already which were added to the example-datasets repository with the Brar 2012 dataset yaml, and will also be able to use the same contaminants file, those files don't need to be duplicated, we can just refer to those existing files in `/annotations` and `/contaminants` in the `/fungi/saccharomyces` folder in the .yaml config file that you'll need to create.  We also don't want to add any of the fastq sample read files, because those are large and we don't want to track those in git version control, like we talked about in today's project meeting. 

This means that to 'add' this dataset to example-datasets, you just need to create a `.yaml` config file in `/fungi/saccharomyces/` folder which contains all the correct provenance information, and the right parameters (including linking to those pre-existing annotation files and contaminant file).  You can probably take a look at the [Brar 2012 yaml file](https://github.com/riboviz/example-datasets/blob/master/fungi/saccharomyces/Brar_2012_Meiosis_RPF_6-samples_CDS_w_250utrs_config.yaml) to see how this is done.  

Something else to bear in mind is that there may have been new yaml parameters created since the Brar dataset was added - you could look into this by checking out the documentation about configuring riboviz [here](https://github.com/riboviz/riboviz/blob/develop/docs/user/prep-riboviz-config.md).  It's also a good place to look to understand more about what each parameter in this yaml file does.

When you go on to add any other *S. cerevisiae* datasets, the process will be the same - you can use the same annotation/contaminants files, just make sure you specify the right parameters and sample files in the yaml.  When you add a different organism dataset, then you'd need to check whether that'll need new annotation files adding (e.g. that'll be the case for #21 *S. pombe* dataset, since that's a new organism to the repo) and also whether it will need a new genus folder adding too. 

Hope this helps!

**Comment by ewallace** [comment]
@FlicAnderson that's a really good note - should some of this go into the repo documentation?

**Comment by ewallace** [comment]
We discussed in the meeting 14/01/2021.

Request
* @3mma-mack and @swinterbourne update this issue ticket with the code they ran and the error message.
* It will help to include information on the filepath from which this is run, e.g. `ls -l` of relevant directories.
* Share the downsampled `fastq.gz` file as a link. (Sharepoint or slack?)
* We will meet to talk through trying to run on Eddie, tomorrow.

**Comment by 3mma-mack** [comment]
Here is the code and error message from running the files on nextflow

`(riboviz) emma@emma-VirtualBox:~/riboviz$ nextflow run prep_riboviz.nf -params-file ../example-datasets/fungi/saccharomyces/Weinberg_2016_RPF_3_samples_CDS_w_250utrs_config.yaml -ansi-log false`
`N E X T F L O W  ~  version 20.10.0`
`Launching 'prep_riboviz.nf' [trusting_thompson] - revision: a48b061e17`
`[1c/5a99e8] Submitted process > cutAdapters (Cerevisiae_RPF)`
`[14/c2b635] submitted > buildIndicesORF (yeast_CDS_w_250)`
`[1c/5a99e8] NOTE: Process 'cutAdapters (Cerevisiae_RPF)' terminated with an error exit status (1) -- Error is ignored`
`No sample was processed successfully
`
We have been having a bit of an issue copying code from the virtual boxes, as it does not seem to work, so hopefully this comes out as the right format

**Comment by swinterbourne** [comment]
The code we ran for the sub-dateset of 40 000 reads on python:

`python -m riboviz.tools.prep_riboviz -c ../example -datasets/fungi/saccharomyces/Weinberg_2016_RPF_3_samples_CDS_w_250utrs_config.yaml`

Error message:

`Problem processing sample: Cerevisae_RPF`
`AssertionError`
`Traceback (most recent call last):`
	`File "/home/sophie/riboviz/riboviz/tools/prep_riboviz.py", line 524, in process_samples 
		sample_logs_dir, run_config)`
	`File "/home/sophie/riboviz/riboviz/tools/prep_riboviz.py", line 302, in process_sample
		run_config)`
	`File "/home/sophie/riboviz/riboviz/workflow.py", line 155, in cut_adapters
		run_config.is_dry_run)`
	`File "/home/sophie/riboviz/riboviz/process_utils.py", line 130, in run_logged_command
		run_command(cmd, f, f)`
	`File "/home/sophie/riboviz/riboviz/process_utils.py" line 22, in run_command
		assert exit_code == 0, "%s failed with exit code %d" % (cmd, exit_code)`
`AssertionError: ['cutadapt', '--trim-n', '-O', '1', '-m', '5', '-a', 'TCGTATGCCGTCTTCTGCTTG', 'o', ;W_Sc_2016/tmp/Cerevisae_RPF/trim.fq', 'W_Sc_2016/input/W_Sc_2016_40000.fastq.gz', '-j', '0'] failed with exit code 1`
`Finished processing 1 samples, 1 failed`
`Processing error: ../example-datasets/fungi/saccharomyces/Weinverg_2016_RPF_3_samples_CDS_w_250utrs_config.yaml`
`Exception`
`Traceback (most recent call last):`
	`File "/home/sophie/riboviz/riboviz/tools/prep_riboviz.py", line 832, in prep_riboviz
		run_workflow(config_file, is_dry_run)`
	`File "/home/sophie/riboviz/riboviz/tools/prep_riboviz.py", line 711, in run_workflow
		raise Exception("No samples were processed succesfully")`
`Exception: No samples were processed succesfully`

**Comment by 3mma-mack** [comment]
Here is the result of ls -l on the riboviz directory, which is where we have been running riboviz from 

drwxr-xr-x  2 emma emma  4096 Jan 12 14:15   
drwxr-xr-x  2 emma emma  4096 Jan 12 14:15   
drwxr-xr-x  2 emma emma  4096 Jan 12 14:15

**Comment by 3mma-mack** [comment]
Here is the information produced after using ls -l on the riboviz directory, which is where we have been running riboviz. 

`drwxr-xr-x  2 emma emma   4096 Jan 12 14:15   bash`
`drwxr-xr-x  4 emma emma   4096 Jan 12 14:15   code-docs`
`drwxr-xr-x  4 emma emma   4096 Jan 12 14:15   data`
`drwxr-xr-x  6 emma emma   4096 Jan 12 14:15   docs`
`-rw-r--r--  1 emma emma 11357 Jan 12 14:15   LICENSE  `
`-rw-r--r--  1 emma emma 40097 Jan 12 14:15   prep_riboviz.nf`
`-rw-r--r--  1 emma emma   8542 Jan 12 14:15   README.md`
`drwxr-xr-x  5 emma emma   4096 Jan 12 14:17   riboviz   `
`-rw-r--r--  1 emma emma  14846 Jan 14 14:17   riboviz.20210114-141728.log   `
`-rw-r--r--  1 emma emma  14846 Jan 14 14:31   riboviz.20210114-143135.log  ` 
`-rw-r--r--  1 emma emma  32963 Jan 14 14:33   riboviz.20210114-143302.log`
`-rw-r--r--  1 emma emma    5533 Jan 14 14:35   riboviz.20210114-143511.log`
`-rw-r--r--  1 emma emma  32963 Jan 14 14:56   riboviz.20210114-145617.log`
`-rw-r--r--  1 emma emma  28672 Jan 14 16:29   riboviz.20210114-162931.log`
`drwxr-xr-x  2 emma emma  4096 Jan 12 14:15    rmarkdown `
`drwxr-xr-x  3 emma emma  4096 Jan 12 14:15    rscripts` 
`-rw-r--r--  1 emma emma    5157 Jan 14 14:35   run_riboviz_vignette.sh`
`drwxr-xr-x  3 emma emma  4096 Jan 12 18:37    vignette  `
`drwxr-xr-x  45 emma emma  4096 Jan 12 20:02   work`
`drwxr-xr-x  3 emma emma  4096 Jan 14 14:19   W_Sc_2016  `

The fastq weinberg data is in W_Sc_2016 in a folder called input 
To get to the yaml, from here we would use `cd ../example-datasets/fungi/saccharomyces`, which takes us to the relevant directory.

**Comment by 3mma-mack** [comment]
We looked into the logs of the failed riboviz run and came across this message in the cutadapt log 

`This is the cutadapt 1.18 with python 3.7.9`
`command line parameters: --trim-n -O 1 -m 5 -a TCGTATGCCGTCTTCTGCTTG -o`
`W_Sc_2016/tmp/Cerevisiae_RPF/trim.fq W_Sc_2016/input/`
`SRR1049521_40000_reads.fastq.gz -j 0`
`Processing reads on 1 core in single-end mode ...`
`cutadapt: error: In read named "SRR1049521.264616 WIGTC-HISEQ:`
`4:1107:15807:29702/1': length of quality sequence (9) and length of read (40) do not match`

After a chat with Edward we believe this is error due to a truncated read in our subsampled dataset

**Comment by kavousan** [comment]
Good detective work. Is there an obvious or preferred way forward?

**Comment by ewallace** [comment]
@3mma-mack , @swinterbourne, and I talked this morning. I suspect that the error arises from truncation of the input `fastq.gz` file, specifically in the middle of the read `SRR1049521.264616`. So the obvious way forward is to re-make a downsampled fastq file and check that it has all complete entries.

There seem to be many fastq checkers/validators; I recommend FASTQC.

Warning of known bug: downsampled fastq files can create errors in `generate_stats_figs.R` if none of the genes exceed `read_count_threshold` so variables end up empty. That can be solved by setting `read_count_threshold = 1` during debugging.

**Comment by 3mma-mack** [comment]
I checked the files and they were indeed truncated, and remaking the files with `head -n` resulted in more errors being produced, at cutadapt files were either corrupted or apparently had unexpected information in line 3 instead of a +, though when I checked the file it appeared to be normal.

So I found another method of subsampling fastq files; `zcat file.fastq.gz  | awk '(NR<=400000)' > subset.fastq `. The file produced here ran until samtools, producing the error `samtools sort: couldn't allocate memory for bam_mem` which is one of the potential errors mentioned in the prep-riboviz-run document.

**Comment by 3mma-mack** [comment]
I've fixed the samtools error, and the sample is now running up to umi_tools_dedup before exiting, producing the error: 

`ValueError: 'a' cannot be empty unless no samples are taken`

So it's getting further but I'm not sure where to go from here as I'm not sure what 'a' is.

**Comment by swinterbourne** [comment]
The 'a' error was at `umi_tools_dedup` and was resolved by ignoring the deduplication as per Edwards suggestion. The run then went further before exiting with the error occurring in bam_to_h5 with: 

`Error: Exception` 

This is likely due to the computer crashing.

**Comment by ewallace** [comment]
_If_ your computer decides not to crash, then this is a good opportunity to try nextflow's resume-where-it-left-off ability, [demystified in a blogpost](https://www.nextflow.io/blog/2019/demystifying-nextflow-resume.html).

Alternatively, this may be a sign that it's time for @3mma-mack and @swinterbourne to move to running on a more powerful computer, i.e. Eddie.

**Comment by FlicAnderson** [comment]
Agreed with @3mma-mack & @swinterbourne to focus on completing and running this on Eddie AFTER 27th Jan (literature review deadline), by which time both should have access to the lab group home space on Eddie (this had been causing errors), and priority queue permissions.

**Comment by 3mma-mack** [comment]
I attempted to run the Weinberg dataset through the python workflow on Eddie in the master branch. It made it passed `bam_to_h5` but failed with exit code 1 during `generate_stats_figs`.
The following error was found in `generate_stats_figs.log`:

```

[1] "Starting: Correlations between TPMs of genes with their sequence-based features"
Saving 7 x 7 in image
Error: Faceting variables must have at least one value
Backtrace:
     █
  1. └─global::WriteSequenceBasedFeatures(features_plot)
  2.   └─ggplot2::ggsave(...)
  3.     ├─grid::grid.draw(plot)
  4.     └─ggplot2:::grid.draw.ggplot(plot)
  5.       ├─base::print(x)
  6.       └─ggplot2:::print.ggplot(x)
  7.         ├─ggplot2::ggplot_build(x)
  8.         └─ggplot2:::ggplot_build.ggplot(x)
  9.           └─layout$setup(data, plot$data, plot$plot_env)
 10.             └─ggplot2:::f(..., self = self)
 11.               └─self$facet$compute_layout(data, self$facet_params)
 12.                 └─ggplot2:::f(...)
 13.                   ├─ggplot2:::unrowname(...)
 14.                   │ └─base::is.data.frame(x)
 15.                   └─ggplot2::combine_vars(data, params$plot_env, vars, drop = params$drop)
Execution halted



```

So the `bam_to_h5` error seems to be due to my laptop as nothing else was changed. Next step after a chat with Flic is to try nextflow and see if the same error occurs in both python and nextflow.

**Comment by 3mma-mack** [comment]
> Warning of known bug: downsampled fastq files can create errors in `generate_stats_figs.R` if none of the genes exceed `read_count_threshold` so variables end up empty. That can be solved by setting `read_count_threshold = 1` during debugging.

Having failed on again on nextflow with my subsampled file I double checked the config.yaml and remembered this suggestion so changed the count_threshold to 1. However this has also failed with the same error

**Comment by FlicAnderson** [comment]
Thwarted on troubleshooting the blocker here (error [riboviz/#277](https://github.com/riboviz/riboviz/issues/277)) by Eddie being temporarily shut down to try and resolve storage errors.

In case it's useful for future diagnosis, *input/output errors* and *issues writing to files* (e.g. even just copying a file from one location to another) seem to be an indication that Eddie has fallen over (in this particular manner, at least). Likewise, issues logging into an interactive session might be an indication. 

I'll check back on the [IS Alerts alert info](https://alerts.is.ed.ac.uk/index.cfm?fuseaction=view_alert&alert_id=9888) tomorrow and have another go at investigating when Eddie is back up and running.

**Comment by 3mma-mack** [comment]
I tried to run a subsample of the Weinberg dataset that I had produced using subsample_bioseqfile.py on eddie and I'm running into errors with `cutadapt`. However I tried running the subsampled dataset that had previously made it to `generate_stats_figs` and this is now also failing at `cutadapt`. I am running this in an interactive session with 16G on the develop branch.
This is the error message I receive is

```
(riboviz) [s1734289@node3c04(eddie) riboviz]$ python -m riboviz.tools.prep_riboviz -c W_Sc_2016/Weinberg_2016_RPF_3_samples_CDS_w_250utrs_config.yaml
Running under Python: 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50)
[GCC 7.5.0]
Created by: RiboViz Date: 2021-02-10 14:44:07.875190 Command-line tool: /exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/tools/prep_riboviz.py File: /exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/tools/prep_riboviz.py Version: commit 7e62c9f8da4f66f9c18aca30394f44fa4a7fa1ef date 2021-01-20 10:18:00-08:00
Configuration file: W_Sc_2016/Weinberg_2016_RPF_3_samples_CDS_w_250utrs_config.yaml
Command file: run_riboviz_W-Sc_2016.sh
Number of processes: 2
Build indices for alignment, if necessary/requested
Build indices for alignment (../../riboviz/example-datasets/fungi/saccharomyces/contaminants/Saccharomyces_cerevisiae_yeast_rRNA_R64-1-1.fa). Log: W_Sc_2016/logs/20210210-144407/hisat2_build_r_rna.log
Build indices for alignment (../../riboviz/example-datasets/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.fa). Log: W_Sc_2016/logs/20210210-144407/hisat2_build_orf.log
Processing samples
Processing sample: Cerevisiae_RPF
Processing file: W_Sc_2016/input/SRR1049521_zcat_40000subset.fastq.gz
Cut out sequencing library adapters. Log: W_Sc_2016/logs/20210210-145244/Cerevisiae_RPF/01_cutadapt.log
Problem processing sample: Cerevisiae_RPF
AssertionError
Traceback (most recent call last):
  File "/exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/tools/prep_riboviz.py", line 524, in process_samples
    sample_logs_dir, run_config)
  File "/exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/tools/prep_riboviz.py", line 302, in process_sample
    run_config)
  File "/exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/workflow.py", line 155, in cut_adapters
    run_config.is_dry_run)
  File "/exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/process_utils.py", line 130, in run_logged_command
    run_command(cmd, f, f)
  File "/exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/process_utils.py", line 22, in run_command
    assert exit_code == 0, "%s failed with exit code %d" % (cmd, exit_code)
AssertionError: ['cutadapt', '--trim-n', '-O', '1', '-m', '5', '-a', 'TCGTATGCCGTCTTCTGCTTG', '-o', 'W_Sc_2016/tmp/Cerevisiae_RPF/trim.fq', 'W_Sc_2016/input/SRR1049521_zcat_40000subset.fastq.gz', '-j', '0'] failed with exit code 1
Finished processing 1 samples, 1 failed
Processing error: W_Sc_2016/Weinberg_2016_RPF_3_samples_CDS_w_250utrs_config.yaml
Exception
Traceback (most recent call last):
  File "/exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/tools/prep_riboviz.py", line 832, in prep_riboviz
    run_workflow(config_file, is_dry_run)
  File "/exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/tools/prep_riboviz.py", line 711, in run_workflow
    raise Exception("No samples were processed successfully")
Exception: No samples were processed successfully
3:09

```
And in the cutadapt W_Sc_2016/logs for the run I found this:
```
This is cutadapt 2.10 with Python 3.7.6
Command line parameters: --trim-n -O 1 -m 5 -a TCGTATGCCGTCTTCTGCTTG -o W_Sc_2016/tmp/Cerevisiae_RPF/trim.fq W_Sc_2016/$
Traceback (most recent call last):
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/bin/cutadapt", line 10, in <module>
    sys.exit(main())
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/site-packages/cutadapt/__mai$
    outfiles = open_output_files(args, default_outfile, file_opener)
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/site-packages/cutadapt/__mai$
    out, out2 = file_opener.xopen_pair(args.output, args.paired_output, "wb")
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/site-packages/cutadapt/utils$
    file1 = self.xopen_or_none(path1, mode)
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/site-packages/cutadapt/utils$
    return self.xopen(path, mode)
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/site-packages/cutadapt/utils$
    return xopen(path, mode, compresslevel=self.compression_level, threads=self.threads)
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/site-packages/xopen/__init__$
    return open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'W_Sc_2016/tmp/Cerevisiae_RPF/trim.fq'
```
In W_Sc_2016/tmp the following files were found
```
dedup.bam        nonrRNA.fq             orf_map_clean.sam      pre_dedup.bam         rRNA_map.sam          unaligned.fq
dedup.bam.bai    orf_map_clean.bam      orf_map.sam            pre_dedup.bam.bai     trim_5p_mismatch.tsv
extract_trim.fq  orf_map_clean.bam.bai  post_dedup_groups.tsv  pre_dedup_groups.tsv  trim.fq
```
So trim.fq is present. 

The next planned steps are to attempt to run the Brar dataset, as this has been run successfully on Eddie before. This will check that the overall process is working correctly 
From there, the original SRR1049521.fastq.gz file could be redownloaded and a run with the full Weinberg dataset attempted on Eddie.

**Comment by FlicAnderson** [comment]
@3mma-mack I've just taken another look at this and noticed in your last error message "FileNotFoundError:" it's looking for: `W_Sc_2016/tmp/Cerevisiae_RPF/trim.fq`. 

I'm not 100% sure, because you haven't included the command and don't show the command prompt where you listed those files, but I think the issue is that folder `Cerevisiae_RPF` doesn't exist.

You can see `W_Sc_2016/tmp/trim.fq`, but it's looking for `W_Sc_2016/tmp/Cerevisiae_RPF/trim.fq`. 
Something's odd here.

I'm not sure off the top of my head where the `Cerevisiae_RPF` folder is created, but I think this is a step done by the nextflow code, not the cutadapt command, so I think the error is before the cutadapt step?

**Comment by FlicAnderson** [comment]
I think running Brar is a good next step, but for when you next attempt the Weinberg dataset, as I think I mentioned in chat earlier, I'd delete it all (W_Sc_2016 folder and everything within it) and set it up again in case some of it got messed up in *the great Eddie I/O Bork of 2021*.

**Comment by 3mma-mack** [comment]
> @3mma-mack I've just taken another look at this and noticed in your last error message "FileNotFoundError:" it's looking for: `W_Sc_2016/tmp/Cerevisiae_RPF/trim.fq`.
> 
> I'm not 100% sure, because you haven't included the command and don't show the command prompt where you listed those files, but I think the issue is that folder `Cerevisiae_RPF` doesn't exist.
> 
> You can see `W_Sc_2016/tmp/trim.fq`, but it's looking for `W_Sc_2016/tmp/Cerevisiae_RPF/trim.fq`.
> Something's odd here.
> 
> I'm not sure off the top of my head where the `Cerevisiae_RPF` folder is created, but I think this is a step done by the nextflow code, not the cutadapt command, so I think the error is before the cutadapt step?

Sorry that was my mistake when writing the update, I double checked and the files are in W_Sc_2016/tmp/Cerevisiae_RPF. I have updated the comment.

```
[s1734289@login01(eddie) riboviz]$ cd W_Sc_2016/tmp/Cerevisiae_RPF/
[s1734289@login01(eddie) Cerevisiae_RPF]$ ls
dedup.bam        nonrRNA.fq             orf_map_clean.sam      pre_dedup.bam         rRNA_map.sam          unaligned.fq
dedup.bam.bai    orf_map_clean.bam      orf_map.sam            pre_dedup.bam.bai     trim_5p_mismatch.tsv
extract_trim.fq  orf_map_clean.bam.bai  post_dedup_groups.tsv  pre_dedup_groups.tsv  trim.fq
```

**Comment by 3mma-mack** [comment]
I attempted to run one of the samples, VEG_1: SRR387871.fastq.gz, from the Brar dataset overnight using both python and nextflow as jobs. Neither of these finished, but neither of them produced errors so I may have interrupted the process somehow. 

The job output file for the Brar nextflow run showed it stopped at `samViewSort`

```
N E X T F L O W  ~  version 20.04.1
Launching `prep_riboviz.nf` [elegant_brenner] - revision: 16531346ed
[15/928880] Submitted process > buildIndicesrRNA (yeast_rRNA)
[77/d05199] Submitted process > cutAdapters (VEG_1)
[03/5506cc] Submitted process > buildIndicesORF (yeast_CDS_w_250)
[5f/27c194] Submitted process > hisat2rRNA (VEG_1)
[eb/834ee6] Submitted process > hisat2ORF (VEG_1)
[44/577175] Submitted process > trim5pMismatches (VEG_1)
[5a/0ef6cf] Submitted process > samViewSort (VEG_1)
```
To investigate further I went into `work/5a/0ef6cfcf7262f2e94182de88220e14/`. 

```
s1734289@login02(eddie) 0ef6cfcf7262f2e94182de88220e14]$ ls -a
.  ..  .command.begin  .command.err  .command.log  .command.out  .command.run  .command.sh  orf_map_clean.sam

```
.command.begin and.command.err were empty, and both .commad.out and .command.log only contained the following:

```
samtools 1.10
Using htslib 1.10.2
Copyright (C) 2019 Genome Research Ltd.

```
.command.sh contained:
```

#!/bin/bash -ue
samtools --version
samtools view -b orf_map_clean.sam | samtools sort              -@ 16 -O bam -o orf_map_clean.bam -
samtools index orf_map_clean.bam
```
and .command.run contained 106 lines of code that I can send if you need but I don't want to make this message too long

For the python workflow The process ran to `bam_to_h5 `. The job output file was as follows 

```
Running under Python: 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50)
[GCC 7.5.0]
Created by: RiboViz Date: 2021-02-10 21:57:40.610400 Command-line tool: /exports/eddie/scratch/s1734289/riboviz/riboviz/riboviz/tools/prep_ribovi$
Configuration file: B-Sc_2012/Brar_2012_Meiosis_RPF_6-samples_CDS_w_250utrs_config.yaml
Command file: run_riboviz_B-Sc_2012.sh
Number of processes: 16
Build indices for alignment, if necessary/requested
Build indices for alignment (../../riboviz/example-datasets/fungi/saccharomyces/contaminants/Saccharomyces_cerevisiae_yeast_rRNA_R64-1-1.fa). Log$
Build indices for alignment (../../riboviz/example-datasets/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.fa). Log:$
Processing samples
Processing sample: VEG_1
Processing file: B-Sc_2012/input/SRR387871.fastq.gz
Cut out sequencing library adapters. Log: B-Sc_2012/logs/20210210-215740/VEG_1/01_cutadapt.log
Remove rRNA or other contaminating reads by alignment to rRNA index files. Log: B-Sc_2012/logs/20210210-215740/VEG_1/02_hisat2_rrna.log
Align remaining reads to ORFs index files using hisat2. Log: B-Sc_2012/logs/20210210-215740/VEG_1/03_hisat2_orf.log
Trim 5' mismatches from reads and remove reads with more than 2 mismatches. Log: B-Sc_2012/logs/20210210-215740/VEG_1/04_trim_5p_mismatch.log
Convert SAM to BAM and sort on genome. Log: B-Sc_2012/logs/20210210-215740/VEG_1/05_samtools_view_sort.log
Index BAM file. Log: B-Sc_2012/logs/20210210-215740/VEG_1/06_samtools_index.log
Calculate transcriptome coverage for + strand and save as a bedgraph. Log: B-Sc_2012/logs/20210210-215740/VEG_1/07_bedtools_genome_cov_plus.log
Calculate transcriptome coverage for - strand and save as a bedgraph. Log: B-Sc_2012/logs/20210210-215740/VEG_1/08_bedtools_genome_cov_minus.log
Make length-sensitive alignments in H5 format. Log: B-Sc_2012/logs/20210210-215740/VEG_1/09_bam_to_h5.log

```
and in `B-Sc_2012/logs/20210210-215740/VEG-1` in log `09-bam_to_h5.log` the following was found was found

```
[1] "Created by: RiboViz"
[1] "Date: 2021-02-10 23:26:47"
[1] "File: /exports/eddie/scratch/s1734289/riboviz/riboviz/rscripts/bam_to_h5.R"
[1] "Version: commit 7e62c9f8da4f66f9c18aca30394f44fa4a7fa1ef date 2021-01-20 18:18:00 GMT"
The following object is masked _by_ .GlobalEnv:

    secondary_id

[1] "bam_to_h5.R running with parameters:"
$num_processes
[1] 16

$min_read_length
[1] 10

$max_read_length
[1] 50

$buffer
[1] 250

$primary_id
[1] "Name"

$secondary_id
[1] "NULL"

$bam_file
[1] "B-Sc_2012/output/VEG_1/VEG_1.bam"

$hd_file
[1] "B-Sc_2012/output/VEG_1/VEG_1.h5"

$orf_gff_file
[1] "../../riboviz/example-datasets/fungi/saccharomyces/annotation/Saccharomyces_cerevisiae_yeast_CDS_w_250utrs.gff3"

$dataset
[1] "B-Sc_2012"

$stop_in_cds
[1] FALSE

$is_riboviz_gff
[1] TRUE

$is_test_run
[1] FALSE

$help
[1] FALSE

[1] "Mapping reads to CDS"
```
As the two processes stopped at different places, but neither produced errors, I am trying running the data through the nextflow pathway in an interactive session with 16G on the develop branch to test this.

**Comment by 3mma-mack** [comment]
Having deleted the W_Sc_2016 folder and all of it's contents, I redownloaded SRR1049521.fasta and zipped the file with `pigz. ` Running a job on Eddie using the full dataset produced the same `generate_stats_figs` error as before so at least we are back to the same place with this as we were before the power cut. So more troubleshooting to go!

**Comment by 3mma-mack** [comment]
@FlicAnderson has done some investigating and found a problem with our UMI regular expression which was previously `^(?P<umi_1>.{8})$` causing the program to look for UMIs at both ends of the strands, which impacted umi_tools_dedup and likely had a knock on effect the rest of the pipeline. She has corrected this to `(?P<umi_1>.{8})` and ran the Weinberg dataset successfully. I have repeated this and it has succeeded again, producing files that do actually contain reads.

I've included the pdf's that were produced here so anyone can check them.

[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/5973983/3nt_periodicity.pdf)
[3ntframe_propbygene.pdf](https://github.com/riboviz/example-datasets/files/5973985/3ntframe_propbygene.pdf)
[codon_ribodens.pdf](https://github.com/riboviz/example-datasets/files/5973987/codon_ribodens.pdf)
[features.pdf](https://github.com/riboviz/example-datasets/files/5973991/features.pdf)
[pos_sp_rpf_norm_reads.pdf](https://github.com/riboviz/example-datasets/files/5973992/pos_sp_rpf_norm_reads.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/5973994/read_lengths.pdf)
[startcodon_ribogrid.pdf](https://github.com/riboviz/example-datasets/files/5973996/startcodon_ribogrid.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/5973998/startcodon_ribogridbar.pdf)

**Comment by ewallace** [comment]
These look great - very nice periodicity etc. It's good enough for me to say it's done. @3mma-mack, please pull request the config file.

What in the documentation do we need to update to make it easier to get UMI regular expressions right sooner in the future?

**Comment by 3mma-mack** [comment]
Looking at the example umi_regexp in [the configuration documentation](https://github.com/riboviz/riboviz/blob/master/docs/user/prep-riboviz-config.md#configuration-parameters) I'd say an example for extracting UMIs from only one end of a strand would be useful, because that would show that '^' and '$' shown in the current examples are not just there as a formatting requirement, which I think is the assumption we made when making the config file.

**Comment by ewallace** [comment]
That's great. Can you make a new issue "add UMI example to documentation" to `riboviz/riboviz` then make a start on the branch etc?
