### ISSUE TITLE
Add Duncan & Mata 2018 Schizosaccharomyces pombe data

### ISSUE THREAD

**Issue by FlicAnderson** [riboviz/example-datasets#21]
Via: [riboviz/#29](https://github.com/riboviz/riboviz/issues/29#issuecomment-520508374)

Add the Duncan & Mata 2018 S. pombe dataset to example-datasets.

**Comment by ewallace** [comment]
Assigning to @3mma-mack and @swinterbourne, *after* they have addressed #20.

This issue relies on creating a new riboviz-style transcript fasta and gff file for *S. pombe*, and testing this with `check_fasta_gff.py`, as noted on [riboviz#74](https://github.com/riboviz/riboviz/issues/74).

**Comment by 3mma-mack** [comment]
I found @ewallace's comment about UMI's in the Duncan and Mata dataset and thought it'd be useful to have a note of them here https://github.com/riboviz/riboviz/issues/29#issuecomment-520508374

**Comment by 3mma-mack** [comment]
I have created rRNA.fasta and rRNA_provenance.txt files to the [contaminants ]( https://github.com/riboviz/example-datasets/tree/S_pombe_Duncan-46/fungi/schizosaccharomyces/contaminants) folder in the newly created Schizosaccharomyces folder in the branch S_pombe_Duncan-46. I have tried to make the format of the provenance files as similar to the provenance files of other species as possible, and the fasta file was created by downloading all off the rRNA files from [Pombase](https://www.pombase.org/results/from/id/3bd9d164-de76-40aa-9294-7e805fd3da25 ) at once which produced a fasta file with all of the rRNA and information on the location of each. I compared the file format to those of other species and it seems to be correct but is there a way for me to check it is as expected?

**Comment by 3mma-mack** [comment]
I have started making a config file for the dataset and have found all documentation of all the [ribosome profiling fasta files](https://www.ncbi.nlm.nih.gov/Traces/study/?acc=ERP023462&f=rna_source_sam_s%3An%3Aribosome%2520protected%2520fragments%2520(rpf)%3Ac&o=acc_s%3Aa) along with the conditions used

**Comment by 3mma-mack** [comment]
I decided to do a test run of the D-Sp_2018 dataset using a newly generated [config yaml](https://github.com/riboviz/example-datasets/blob/S_pombe_Duncan-46/fungi/schizosaccharomyces/Duncan_2018_amino_acid_starved_CDS_w_250utrs_config.yaml), the fasta and gff files generated by @acope3 in issue #46  and an rRNA contaminants file. It ran successfully and produced the following graphs, which I think look pretty reasonable 
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6103409/read_lengths.pdf)
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6103410/3nt_periodicity.pdf)
[pos_sp_rpf_norm_reads.pdf](https://github.com/riboviz/example-datasets/files/6103411/pos_sp_rpf_norm_reads.pdf)
[startcodon_ribogrid.pdf](https://github.com/riboviz/example-datasets/files/6103412/startcodon_ribogrid.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6103413/startcodon_ribogridbar.pdf)

I was curious as to if there would be an obvious difference if the fasta and gff files used contained a lot of errors, such as ones I had been producing, which are still containing a lot of errors, over 6000 now I am filtering for both CDS and mRNA.

[features_issues_08_03.txt](https://github.com/riboviz/example-datasets/files/6103447/features_issues_08_03.txt)

Using these files for annotation produced the following graphs:

[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6103458/read_lengths.pdf)
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6103460/3nt_periodicity.pdf)
[pos_sp_rpf_norm_reads.pdf](https://github.com/riboviz/example-datasets/files/6103461/pos_sp_rpf_norm_reads.pdf)
[startcodon_ribogrid.pdf](https://github.com/riboviz/example-datasets/files/6103462/startcodon_ribogrid.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6103463/startcodon_ribogridbar.pdf)

The reads at the 5' end do not show clear 3nt periodicity, and this has definitely shown me the importance of having good quality transcriptome gff and fasta files.

**Comment by ewallace** [comment]
Discussed on 2012-03-10, agreed that next step is for @3mma-mack to upload the config.yaml file including provenance, and update the issue ticket.
