### ISSUE TITLE
Add Archaea dataset

### ISSUE THREAD

**Issue by acope3** [riboviz/example-datasets#28]
Allen Buskirk's lab has done ribosome profiling on the themorphilic archaea Haloferax volcanii DS2 ([GSE138990](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE138990)). Adding this dataset means our example-datasets spans the domains of life and it will be the first extremophile we've analyzed.

**Comment by acope3** [comment]
See pull request #29

**Comment by ewallace** [comment]
That's amazing - can you share any of the QC (e.g. 3nt-periodicity) plots just so we can see how they look?

**Comment by acope3** [comment]
[Flash_freeze_w_centrifugation_3ntframe_propbygene.pdf](https://github.com/riboviz/example-datasets/files/5599219/Flash_freeze_w_centrifugation_3ntframe_propbygene.pdf)
[Flash_freeze_w_centrifugation_3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/5599221/Flash_freeze_w_centrifugation_3nt_periodicity.pdf)
[MNase_3ntframe_propbygene.pdf](https://github.com/riboviz/example-datasets/files/5599225/MNase_3ntframe_propbygene.pdf)
[MNase_3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/5599226/MNase_3nt_periodicity.pdf)


These correspond to two of the measurements on [GSE138990](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE138990). Figured I would upload both so you could compare and contrast.

**Comment by kavousan** [comment]
@ewallace reported the graphs look good.
@FlicAnderson to run these on Eddie.
