### ISSUE TITLE
Add per-codon simulated data to example-dataset

### ISSUE THREAD

**Issue by FlicAnderson** [riboviz/example-datasets#31]
Re: https://github.com/riboviz/riboviz/issues/112#issuecomment-748384256 

Add @amandamok 's per-codon simulated data as an example-dataset in this repo.

**Comment by ewallace** [comment]
I'm going to attack this now, because it's the best way to prepare for [riboviz#238](https://github.com/riboviz/riboviz/issues/238). Agreed with @FlicAnderson.

**Comment by ewallace** [comment]
* Created branch `sim-percodon-31`.
* Made new smaller annotation files, with just the 5 genes, `Scer_YAL_5genes_w_250utrs.*`, in `simulated/mok/annotation.
* Drafted `Mok-simYAL5_config.yaml`

Next step is to pull to Eddie and see if it will run on an interactive node.

**Comment by ewallace** [comment]
I ran this dataset through riboviz on Eddie, `develop` branch commit 8e61429

The code I ran after logging on to Eddie


## Set up data input directory

```
mkdir /exports/eddie/scratch/$USER/Mok-simYAL5
cd /exports/eddie/scratch/$USER/Mok-simYAL5
mkdir input
cd input 
curl -LJO \
  https://github.com/amandamok/simRiboSeq/raw/master/simulation_runs/riboviz/simRiboviz.fq.gz
cd /home/$USER/riboviz/riboviz
ln -s /exports/eddie/scratch/$USER/Mok-simYAL5
```

## Run riboviz

```
qlogin -pe interactivemem 4 -l h_vmem=4G -P bio_wallace_rna_riboviz
source set-riboviz-env.sh
cd riboviz/riboviz

nextflow run prep_riboviz.nf -params-file ../example-datasets/simulated/mok/Mok-simYAL5_config.yaml
```

This ran with output as expected (from filenames). I still need to check the output for sense/correctness.

**Comment by ewallace** [comment]
Output is ok for consistency! Checked against @amandamok's original [simRiboviz_footprint_counts.txt](https://github.com/amandamok/simRiboSeq/blob/master/simulation_runs/riboviz/simRiboviz_footprint_counts.txt).

R code to summarize the input simulated counts:

```{r}
> library(tidyverse)

> count_df <- readr::read_tsv("simRiboviz_footprint_counts.txt")

> count_df %>%
>     dplyr::group_by(transcript) %>%
>     dplyr::summarise(readcount = sum(cts))

# A tibble: 5 x 2
  transcript readcount
  <chr>          <dbl>
1 YAL003W       228586
2 YAL005C       170563
3 YAL012W       248068
4 YAL035W       153513
5 YAL038W       199270

> count_df %>%
>     dplyr::group_by(length) %>%
>     dplyr::summarise(readcount = sum(cts))
    
# A tibble: 5 x 2
  length readcount
   <dbl>     <dbl>
1     27    159135
2     28    277897
3     29    318776
4     30    177961
5     31     66231
```

Riboviz output agrees, giving same numbers for `tpms.tsv`:

```
# Created by: RiboViz
# Date: 2021-01-12 16:49:57
# File: /exports/eddie3_homes_local/ewallac2/riboviz/riboviz/rscripts/generate_stats_figs.R
# Version: commit 8e61429583e2fd7e9c2ba6c5d6a3b7224e53d174 date 2021-01-11 10:40:22 GMT
ORF	readcount	rpb	tpm
YAL003W	228586	342.194610778443	423162.311190211
YAL005C	170563	86.3173076923077	106741.10657588
YAL012W	248068	201.353896103896	248996.849624979
YAL035W	153513	50.2333115183246	62119.1670800304
YAL038W	199270	128.561290322581	158980.5655289
```

Also numbers for `read_lengths.tsv`:

```
# Created by: RiboViz
# Date: 2021-01-12 16:49:53
# File: /exports/eddie3_homes_local/ewallac2/riboviz/riboviz/rscripts/generate_stats_figs.R
# Version: commit 8e61429583e2fd7e9c2ba6c5d6a3b7224e53d174 date 2021-01-11 10:40:22 GMT
Length	Counts
10	0
[...]
26	0
27	159135
28	277897
29	318776
30	177961
31	66231
32	0
[...]
```

Here is the "ribogrid" plot around the start codon. 
[startcodon_ribogrid.pdf](https://github.com/riboviz/example-datasets/files/5804020/startcodon_ribogrid.pdf)

Requesting review from @amandamok in case I missed anything.

This data (and the code above) should then be useful test data for [riboviz#238](https://github.com/riboviz/riboviz/issues/238).

**Comment by amandamok** [comment]
Looks great!
