### ISSUE TITLE
E. coli annotation provenance

### ISSUE THREAD

**Issue by ewallace** [riboviz/example-datasets#40]
Request 
* provenance information for E. coli annotation files, as described in the repo's `README.md`
* README.md for ecoli folder to briefly summarize contents.

**Comment by ewallace** [comment]
Created new branch `ecoli-provenance-40`. I pushed a couple of things there, including renaming the `annotations` folder to `annotation` to be consistent with other files and the repo's `README.md`. It might be better to call those folders `annotations` in plural, as long as we're consistent across example-datasets.

**Comment by acope3** [comment]
See pull request #59.
