### ISSUE TITLE
Add .fai and other files to .gitignore

### ISSUE THREAD

**Issue by ewallace** [riboviz/example-datasets#41]
Running `check_fasta_gff` (in fact `gffutils.create_db`), on a fasta file (e.g. `example.fa`) automatically creates fasta index files (e.g. `example.fa.fai`) in the same directory.

Adding files with extension `.fai` in child directories to `.gitignore` would make it easier to avoid committing those.

Which other files should we automatically exclude? If we could exclude files with extensions `.fastq`, `.fastq.gz`, `.fq`, `.fq.gz`, `bam`, `sam`, that would make it easier for anyone avoid accidentally committing those.

**Comment by FlicAnderson** [comment]
Pull request #106 closes this issue
