### ISSUE TITLE
Adding Morgan et.al. 2018 E. coli heat stress dataset

### ISSUE THREAD

**Issue by acope3** [riboviz/example-datasets#47]
As part of my personal interest in the effects of heat stress on mRNA translation/evolution and a desire to further test the download SRA feature  (riboviz Issue #207), I wanted to apply riboviz to the dataset from this [paper](https://www.jbc.org/article/S0021-9258(20)39654-X/fulltext) ([GSE90056](http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE90056)). I think it would be good to add to example-datasets.

A couple of things:
(1) I noticed that contaminants file for E. coli K12 is missing.
(2) I still need to add a provenance file for E. coli (see #40)

I can take care of these two issues when adding the Morgan et. al. example, unless anyone thinks it's better to split these up into three separate pull requests.

**Comment by ewallace** [comment]
Sounds great! It makes sense to me to solve these related issues in a single pull request .

**Comment by acope3** [comment]
See pull request #59.
