### ISSUE TITLE
Update kingdom-level README files

### ISSUE THREAD

**Issue by ewallace** [riboviz/example-datasets#50]
Kingdom-level README files could & should reflect the datasets that have been added in the genus-specific directories.

**Comment by FlicAnderson** [comment]
Personally I think we should avoid 'informal' naming conventions like "ecoli" and stick with the full scientific name "Escherichia coli" or "E. coli" usage in READMEs, and certainly avoid any common naming (e.g. "mouse" or "fly" or "yeast"). In file names, we can substitute the '.' for a '-' if necessary.

This makes it easier to discover the files through searches if we do this, as well as not making taxonomists cry :sweat_smile:
