### ISSUE TITLE
Update name for hvolcanii.yaml?

### ISSUE THREAD

**Issue by ewallace** [riboviz/example-datasets#53]
So `archaea/hvolcanii/hvolcanii.yaml` just has the species name in the config.yaml title. Given that in principle another dataset might appear soon for the same organism, it would be more precise to describe as `Gelsinger2020_hvolcanii.yaml`.

I note that this author-year name format, used in most of the fungal datasets, is not currently described in the repo README.md `https://github.com/riboviz/example-datasets#configyaml`

@acope3 do you think we should be more precise about the name? OR change how we do yaml names?

Also requesting 2nd opinion from @FlicAnderson.

**Comment by ewallace** [comment]
@FlicAnderson 's opinion (from #50):
> Personally I think we should avoid 'informal' naming conventions like "ecoli" and stick with the full scientific name "Escherichia coli" or "E. coli" usage in READMEs, and certainly avoid any common naming (e.g. "mouse" or "fly" or "yeast"). In file names, we can substitute the '.' for a '-' if necessary.

> This makes it easier to discover the files through searches if we do this, as well as not making taxonomists cry :sweat_smile:

**Comment by acope3** [comment]
I agree that names like "mouse" or "yeast" should be avoided, but I think some variation on Ecoli (with or without the '.' or '-') is appropriate. I think it is also a good idea to add the strain info for bacteria, e.g. "Ecoli_K12" and "Ecoli_Rel606." We just need to make sure we're consistent.

**Comment by acope3** [comment]
See pull request #59.

**Comment by FlicAnderson** [comment]
@acope3 Totally agree on adding strain info for bacteria, good shout.

**Comment by acope3** [comment]
I believe this was addressed as part of pull request #59. I'm going to close this issue.
