### ISSUE TITLE
Comment on simulated/mok/annotation/tiny_2genes_20utrs.gff3 issues

### ISSUE THREAD

**Issue by mikej888** [riboviz/example-datasets#73]
In riboviz, `data/Mok-tinysim-gffsam/tiny_2genes_20utrs.gff3` has a copy of 
[simulated/mok/annotation/tiny_2genes_20utrs.gff3](https://github.com/riboviz/example-datasets/blob/master/simulated/mok/annotation/tiny_2genes_20utrs.gff3) from this repository.

As part of tests for `bam_to_h5.R` in riboviz/riboviz#61, I originally loaded this file, replaced `CDS` with `ORF` then saved it:
```
    gff <- rtracklayer::import(orf_gff_file)
    levels(gff$type)[levels(gff$type) == "CDS"] <- "ORF"
    rtracklayer::export(gff, test_gff_file)
```
However this always gave a warning:
```
The phase information is missing for some CDS. The written file will contain some CDS with no phase information.
```
This causes the test to not fail, but not pass either. Just loading the gff file then saving it, without any changes, gives the same warning.
To avert this warning I set the `Phase` values to 0:
```
    gff$phase <- numeric(length(gff$Name))
```
(see https://github.com/riboviz/riboviz/blob/refactor-bam-to-h5-61/rscripts/tests/testthat/test_bam_to_h5.R, line [576](https://github.com/riboviz/riboviz/blob/e060650d5d1f5abf06d36f05268f399a21471c32/rscripts/tests/testthat/test_bam_to_h5.R#L576) onwards)

Does this imply that `simulated/mok/annotation/tiny_2genes_20utrs.gff3` should explicitly have Phase values? (column 8)?

**Comment by mikej888** [comment]
According to https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md: 

> The phase is one of the integers 0, 1, or 2, indicating the number of bases forward from the start of the current CDS feature the next codon begins. A phase of "0" indicates that a codon begins on the first nucleotide of the CDS feature (i.e. 0 bases forward), a phase of "1" indicates that the codon begins at the second nucleotide of this CDS feature and a phase of "2" indicates that the codon begins at the third nucleotide of this region.

**Comment by mikej888** [comment]
Running the file through http://genometools.org/cgi-bin/gff3validator.cgi (with "use Sequence Ontology to validate types and parent-child relationships" unchecked) gives:

```
Validation successful!

4 issues remaining:

warning: unknown meta-directive encountered in line 2 in file "/var/www/servers/genometools.org/htdocs/cgi-bin/gff3/tiny_2genes_20utrs.gff3", keep anyway: ##ewallace - Edward.Wallace@ed.ac.uk

1		##gff-version 3
2	?	##ewallace - Edward.Wallace@ed.ac.uk
3		##date 2021-01-13
warning: unknown meta-directive encountered in line 3 in file "/var/www/servers/genometools.org/htdocs/cgi-bin/gff3/tiny_2genes_20utrs.gff3", keep anyway: ##date 2021-01-13

2		##ewallace - Edward.Wallace@ed.ac.uk
3	?	##date 2021-01-13
4		MAT	ewallace	UTR5	1	20	.	+	.	Name=MAT
warning: seqid "MAT" on line 4 in file "/var/www/servers/genometools.org/htdocs/cgi-bin/gff3/tiny_2genes_20utrs.gff3" has not been previously introduced with a "##sequence-region" line, create such a line automatically

3		##date 2021-01-13
4	?	MAT	ewallace	UTR5	1	20	.	+	.	Name=MAT
5		MAT	ewallace	CDS	21	32	.	+	.	Name=MAT
warning: seqid "MIKE" on line 7 in file "/var/www/servers/genometools.org/htdocs/cgi-bin/gff3/tiny_2genes_20utrs.gff3" has not been previously introduced with a "##sequence-region" line, create such a line automatically

6		MAT	ewallace	UTR3	33	52	.	+	.	Name=MAT
7	?	MIKE	ewallace	UTR5	1	20	.	+	.	Name=MIKE
8		MIKE	ewallace	CDS	21	35	.	+	.	Name=MIKE
```

**Comment by ewallace** [comment]
Yes, it is appropriate for the phase information to be set to 0 for these CDS in this file.

**Comment by ewallace** [comment]
I do not understand these meta-directives and have not previously used this gff3-validator. It also does not affect our use of the gff3 as a tool for unit & integration tests.

It does raise questions about what formats we should insist on for future riboviz gff3s, as discussed in [address GFF interoperability riboviz#129](https://github.com/riboviz/riboviz/issues/129) and more generally in [ORF-GFF-FASTA issues](https://github.com/riboviz/riboviz/issues?q=+is%3Aissue+label%3AORF-GFF-FASTA+).

**Comment by kavousan** [comment]
Agreed we will not deal with it.
