### ISSUE TITLE
Remove `is_test_run` parameter

### ISSUE THREAD

**Issue by mikej888** [riboviz/example-datasets#74]
This is a legacy parameter and was unused (and has now been removed from YAML files and documentation in `riboviz`, see riboviz/riboviz#300). It should be removed from YAML files and documentation in this repository.

**Comment by FlicAnderson** [comment]
Check this is completed before/during #76

**Comment by mikej888** [comment]
Running `riboviz.tools.upgrade_config_file` will remove `is_test_run`. Closing as duplicated by #76.
