### ISSUE TITLE
Add Guydosh & Green 2014 yeast dataset

### ISSUE THREAD

**Issue by 3mma-mack** [riboviz/example-datasets#83]
The vignette was created using a downsampled version of data from the Guydosh & Green 2014 paper, but the full dataset is not yet present on example datasets. 

[link to paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4022138/) - Nicholas R. Guydosh and Rachel Green. 'Dom34 Rescues Ribosomes in 3´ Untranslated Regions'. _Cell_, 2014 Feb 27;156(5):950-62 

[SRR1042855](https://www.ncbi.nlm.nih.gov/sra/SRX386986[accn]) - Wild type no additive 
[SRR1042864](https://www.ncbi.nlm.nih.gov/sra/?term=SRR1042864) - Wild type 3-AT

**Comment by 3mma-mack** [comment]
Looking through the paper, the methods reference the ingolia et al 2012 paper, which uses the adapter sequence CTGTAGGCACCATCAAT

confusingly the vignette uses the adapter sequence CTGTAGGCACC, a shortened version of the adapter listed above. as the vignette is derived from the Guydosh data it would make sense if they had the same adapter. 

The current plan is to run the data through riboviz twice, testing both adapter sequences and comparing the results

**Comment by swinterbourne** [comment]
The config file for the Guydosh and Green 2014 dataset is in the branch [G-Sc_2014_83](https://github.com/riboviz/example-datasets/blob/G-Sc_2014_83/fungi/saccharomyces/Guydosh_2014_dom34_2-samples_CDS_w_250utrs_config.yaml) in example-datasets

**Comment by ewallace** [comment]
This looks great!

Could you add all the samples from Guydosh and Green 2014? Or at least the other wild-type samples as listed on [SRP033499](https://www.ncbi.nlm.nih.gov//sra/?term=SRP033499). 
* [SRR1042853](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR1042853) - WT CHX
* [SRR1042857](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR1042857) - WT CHX + GMP-PMP (good luck abbreviating that consistently)
* [SRR1042858](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR1042858) - WT GMP-PNP
* [SRR1042859](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR1042859) - WT high-Mg
* [SRR1042868](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR1042868) - WT diamide

WT disomes are spread over 2 SRA files and I don't think riboviz can deal with those yet.

For testing purposes it's fine with me to run only the WT and WT 3-AT. If it's possible to run the whole pipeline on Eddie for those samples, then we would love to show the full-dataset .html output alongside the vignette output in next week's hands-on workshop.

**Comment by 3mma-mack** [comment]
I have tried running the config files with both versions of adapters, however both fail at the step BamToH5. I have looked into the .command.log file for both runs and both contain the following:

```
Error in library(getopt, quietly = T) :
  there is no package called ‘getopt’
Calls: suppressMessages -> withCallingHandlers -> library
Execution halted
```

Having a look, the line library(getopt, quietly = T) appears on line 28 of Bam_to_H5.R, and the package is also present in the wallace_rna/Rlibrary folder on eddie, so I don't understand why it is failing here. I have started a run of the Duncan et al Schizosaccharomyces dataset to see if the error occurs for that dataset as well, as I successfully ran the Duncan et al dataset on the 23rd . 

This is being run in the develop branch of riboviz, with the latest commit being 106a204bc64525db8de7d18e99d5421be1246394, on the 21st of June.

**Comment by swinterbourne** [comment]
> I have tried running the config files with both versions of adapters, however both fail at the step BamToH5. I have looked into the .command.log file for both runs and both contain the following:
> 
> ```
> Error in library(getopt, quietly = T) :
>   there is no package called ‘getopt’
> Calls: suppressMessages -> withCallingHandlers -> library
> Execution halted
> ```
> 
> Having a look, the line library(getopt, quietly = T) appears on line 28 of Bam_to_H5.R, and the package is also present in the wallace_rna/Rlibrary folder on eddie, so I don't understand why it is failing here. I have started a run of the Duncan et al Schizosaccharomyces dataset to see if the error occurs for that dataset as well, as I successfully ran the Duncan et al dataset on the 23rd .
> 
> This is being run in the develop branch of riboviz, with the latest commit being 106a204bc64525db8de7d18e99d5421be1246394, on the 21st of June.

I found a typo in the nextflow_dag_file parameter which I have corrected. This may solve the issue?

**Comment by 3mma-mack** [comment]
Following minor changes to the config file and the job submission script, the Guydosh 2014 dataset has run successfully with the full CTGTAGGCACCATCAAT adapter sequence for samples WT and WT_3-AT. The outputs do look a little messy and the peak read length is around 28. I am running it again with the shorter adapter sequence to see how the results compare.

WT 
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6717569/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6717572/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6717573/startcodon_ribogridbar.pdf)

WT_3-AT
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6717574/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6717577/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6717578/startcodon_ribogridbar.pdf)

**Comment by 3mma-mack** [comment]
Having checked through the job scripts I had been using for the successful and unsuccessful runs, it seems that the problem is I had forgotten to add 'groups' in the path to the Rlibrary when running create_job_script. This means it just wasn't able to find the R packages, and 'getopt' is likely just the first one to be called during the pipeline.

**Comment by swinterbourne** [comment]
> This looks great!
> 
> Could you add all the samples from Guydosh and Green 2014? Or at least the other wild-type samples as listed on [SRP033499](https://www.ncbi.nlm.nih.gov//sra/?term=SRP033499).
> 
> * [SRR1042853](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR1042853) - WT CHX
> * [SRR1042857](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR1042857) - WT CHX + GMP-PMP (good luck abbreviating that consistently)
> * [SRR1042858](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR1042858) - WT GMP-PNP
> * [SRR1042859](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR1042859) - WT high-Mg
> * [SRR1042868](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR1042868) - WT diamide
> 
> WT disomes are spread over 2 SRA files and I don't think riboviz can deal with those yet.
> 
> For testing purposes it's fine with me to run only the WT and WT 3-AT. If it's possible to run the whole pipeline on Eddie for those samples, then we would love to show the full-dataset .html output alongside the vignette output in next week's hands-on workshop.

I have added all of the samples to the config file and pushed those changes. I included the WT disomes in the config but these are commented out. I am currently in the process of downloading all of the files so that I can run the dataset through riboviz. 

I ran into the same issue that Emma did in terms of a typo in the pathways for the job script. After fixing these issues the dataset ran successfully for the Wt and Wt_3-AT samples.

**Comment by ewallace** [comment]
Sounds ideal.

> the problem is I had forgotten to add 'groups' in the path to the Rlibrary when running create_job_script. This means it just wasn't able to find the R packages, and 'getopt' is likely just the first one to be called during the pipeline.

Is this thoroughly covered in the documentation for `create_job_script`, or do we need to change that? Reminder to update issue [riboviz#289](https://github.com/riboviz/riboviz/issues/289), comments on testing the job script.

**Comment by 3mma-mack** [comment]
I think the documentation covers it pretty well, it was just me forgetting to add it while typing. Though we could potentially add a line to say 'if you run into this specific error, it is likely due to a typo in the `--r-libs` parameter.
Ah yes, I'll go add some comments

**Comment by ewallace** [comment]
Could you share with the .html output for WT and WT-3AT? 

Ideally in [workshop-2021-07-02 repo](https://github.com/riboviz/workshop-2021-07-02), probably in a new subdirectory `output`? Or slack if that's too much hassle.

**Comment by swinterbourne** [comment]
The dataset timed out before it complete. I tried to resume with nextflow but the information does not seem to have been retained, I don't know if this is due to the ringfence node going down today. I have restarted the run for the wt samples only as the job will not complete by Friday otherwise.

**Comment by swinterbourne** [comment]
I have run the remaining samples through riboviz with the full CTGTAGGCACCATCAAT adapter sequence, all samples have now been processed excluding the Wt disome samples. 

The 3nt periodicity was messy for some of the samples, especially Dom34KO_Gluc_Starv, Dom34KO_GMP-PNP, Ski2KO_Short, Ski2KO_Dom34KO_Short and Wt_GMP-PNP

The read-lengths were quite spread out for some of the samples including Wt_GMP-PNP, Dom34KO_CHX_GMP-PNP, Ski2KO_Short and Ski2KO_Dom34KO_Short. For the Ski2KO_Short and Ski2KO_Dom34KO_Short samples this may be explained by the short footprints that were included. 

Wt_CHX (SRR1042853):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846771/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846772/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846773/startcodon_ribogridbar.pdf)

Dom34KO_CHX (SRR1042854):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846778/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846779/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846780/startcodon_ribogridbar.pdf)

Wt (SRR1042855):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846787/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846788/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846789/startcodon_ribogridbar.pdf)

Dom34KO (SRR1042856):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846730/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846733/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846735/startcodon_ribogridbar.pdf)

Wt_CHX_GMP-PNP (SRR1042857):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846796/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846799/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846800/startcodon_ribogridbar.pdf)

Wt_GMP-PNP (SRR1042858):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846803/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846804/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846805/startcodon_ribogridbar.pdf)

Wt_High-Mg (SRR1042859):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846810/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846811/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846812/startcodon_ribogridbar.pdf)

Dom34KO_CHX_GMP-PNP (SRR1042860):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846818/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846819/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846821/startcodon_ribogridbar.pdf)

Dom34KO_GMP-PNP (SRR1042861):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846828/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846829/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846830/startcodon_ribogridbar.pdf)

Dom34KO_High-Mg (SRR1042862):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846833/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846834/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846835/startcodon_ribogridbar.pdf)

Ski2KO (SRR1042863):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846839/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846840/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846841/startcodon_ribogridbar.pdf)

Wt_3-AT (SRR1042864):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846846/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846847/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846848/startcodon_ribogridbar.pdf)

Dom34KO_3-AT_1 (SRR1042867):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846852/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846853/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846854/startcodon_ribogridbar.pdf)

Dom34KO_3-AT_2 (SRR1042866):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846856/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846857/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846858/startcodon_ribogridbar.pdf)

Dom34KO_3-AT_3 (SRR1042865):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846864/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846865/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846866/startcodon_ribogridbar.pdf)

Wt_Diamide (SRR1042868):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846875/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846876/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846877/startcodon_ribogridbar.pdf)

Dom34KO_Diamide (SRR1042869):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846883/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846884/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846885/startcodon_ribogridbar.pdf)

Ski2KO_Suppr-tRNA_1 (SRR1042870):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846887/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846888/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846889/startcodon_ribogridbar.pdf)

Ski2KO_Suppr-tRNA_2 (SRR1042871):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846892/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846893/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846894/startcodon_ribogridbar.pdf)

Ski2KO_Suppr-tRNA_3 (SRR1042872):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846905/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846906/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846908/startcodon_ribogridbar.pdf)

Ski2KO_Dom34KO_Suppr-tRNA (SRR1042873):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846914/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846915/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846916/startcodon_ribogridbar.pdf)

Dom34KO_Gluc-Starv (SRR1042874):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846920/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846921/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846922/startcodon_ribogridbar.pdf)

Hbs1KO (SRR1042875):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846926/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846927/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846928/startcodon_ribogridbar.pdf)

Ski2KO_Short (SRR1042876):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846933/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846934/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846935/startcodon_ribogridbar.pdf)

Ski2KO_Dom34KO_Short (SRR1042877):
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/6846939/3nt_periodicity.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/6846940/read_lengths.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/6846941/startcodon_ribogridbar.pdf)
