### ISSUE TITLE
Add new Histoplasma capsulatum species and data from Anita Sil's lab

### ISSUE THREAD

**Issue by swinterbourne** [riboviz/example-datasets#91]
Thanks for starting to add a new dataset to example-datasets! This issue template includes the key steps, see [add-new-dataset.md](https://github.com/riboviz/example-datasets/add-new-dataset.md). Please edit as needed for your dataset.

- [x] Create a new branch of example-datasets with a helpful concise name, for example `cheng-entamoeba-123` if the dataset were generated by Dr. Cheng, from entamoeba, and the new issue ticket is number 123.
- [x] Identify paper or data source - list and link
- [x] Identify the species and strain used, check if example-datasets already has appropriate annotation and contaminant files.
- [x] (if new species) Find annotation data for the species and strain elsewhere.
- [x] (if new species *and* genus)  Create a genus folder in example-datasets.
- [x] (if new species) Download or create contaminants fasta file.
- [x] (if new species) Download or create transcriptome annotation fasta and gff files.
- [x] (if new species) Check annotation files for consistency with `check_fasta_gff`.
- [x] Identify the ribosome profiling samples from the dataset (some may be RNA-seq) - link database.
- [x] Identify adapter sequence - provide sequence.
- [x] Confirm or deny presence of UMIs and barcodes if used - describe if present.
- [x] If UMIs are present, create UMI regular expression.
- [x] Using information gathered, create config file.
- [x] Download sample data.
- [x] (optional) Create downsampled data and fast test run on that.
- [x] Test run of full sized dataset.
- [x] Look at results - check for 3nt periodicity in coding regions, most common read lengths being 28-32 nt, and clear start and stop profiles.
- [x] Troubleshoot as necessary and discuss on issue ticket.
- [x] Update genus-level README.md and provenance section of config file.
- [x] Put in pull request to add to repository.

**Comment by swinterbourne** [comment]
Once species is set up we would like to add the [data](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005395) from Anita Sil's lab.

New branch has been made for adding the new species, available in example-datasets in the branch "add-new-species-HCapsulatum-91".

**Comment by swinterbourne** [comment]
Annotation and contamination files have been added in the annotation and contamination folders within the genus folder. Provenance text files have also been added describing where the files were downloaded from, available in the branch "add-new-species-HCapsulatum-91".

**Comment by swinterbourne** [comment]
The annotation files were checked with the `check_fasta_gff` tool. None of the FASTA sequences aligned to the sequences in the GFF file. 

```
(riboviz) [s1767247@node1h20(eddie) riboviz]$ python -m riboviz.tools.check_fasta_gff \
> -f ../example-datasets/fungi/histoplasma/annotation/Histoplasma_capsulatum_CDS.fasta \
> -g ../example-datasets/fungi/histoplasma/annotation/Histoplasma_capsulatum_CDS.gff3 \
> -o check_HCapsulatum.tsv
Created by: RiboViz
Date: 2021-07-28 14:20:21.055868
Command-line tool: /exports/eddie/scratch/s1767247/riboviz/riboviz/riboviz/tools/check_fasta_gff.py
File: /exports/eddie/scratch/s1767247/riboviz/riboviz/riboviz/tools/check_fasta_gff.py
Version: commit d42defd662a1e4bc00fed9a4f001016ce6ac4084 date 2021-07-28 05:55:25-07:00

Configuration:
fasta_file      ../example-datasets/fungi/histoplasma/annotation/Histoplasma_capsulatum_CDS.fasta
gff_file        ../example-datasets/fungi/histoplasma/annotation/Histoplasma_capsulatum_CDS.gff3
start_codons    ['ATG']

Metadata:
NumSequences    11221
NumFeatures     86770
NumCDSFeatures  0

Issue summary:
Issue   Count
SequenceNotInGFF        11221
IncompleteFeature       0
NoIdName        0
DuplicateFeatureId      0
NoStartCodon    0
SequenceNotInFASTA      0
MultipleCDS     0
NoStopCodon     0
InternalStopCodon       0
DuplicateFeatureIds     0
```

In addition, @3mma-mack spotted sequences marked as being on the negative strand which riboviz does not like. We will therefore download the genome versions of the files and run `create_files_for_riboviz.R` to generate new files and check their consistency again with the `check_fasta_gff` tool.

**Comment by 3mma-mack** [comment]
I am currently trying to run the files with create_files_for_riboviz.R, but am running into errors at remove trailing.

```
[1] "Removing trailing values on gene ids..."
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'X' in selecting a method for function 'sapply': non-character argument
Calls: removeTrailing ... strsplit -> strsplit -> <Anonymous> -> .handleSimpleError -> h
Execution halted
[1] 1
```

I receive this error whether I include the `--remove_trailing` tag or not. When included I've used `\\:` , as these were used when making the pombe annotation file, and when not included the default is `_|\\.` . It is possible that the files have specific trailing symbols so I will see if I can identify these.

Create_files_for_riboviz.R was run with the following command in branch create_riboviz_style_cds_gff_acope3-278 from the riboviz directory. 

`system('Rscript --vanilla rscripts/create_files_for_riboviz.R -i ../example-datasets/fungi/histoplasma/annotation/Histoplasma_capsulatum_CDS.fasta -g ../example-datasets/fungi/histoplasma/annotation/Histoplasma_capsulatum_CDS.fasta --out_dir . --out_cds histo.fasta --out_gff histo.gff3 -s ID -b 250 --remove_trailing \\: --filter_seq type:CDS --exons_preordered')`

`system('Rscript --vanilla rscripts/create_files_for_riboviz.R -i ../example-datasets/fungi/histoplasma/annotation/Histoplasma_capsulatum_CDS.fasta -g ../example-datasets/fungi/histoplasma/annotation/Histoplasma_capsulatum_CDS.fasta --out_dir . --out_cds histo.fasta --out_gff histo.gff3 -s ID -b 250 --filter_seq type:CDS --exons_preordered')`

**Comment by 3mma-mack** [comment]
I've realised I was listing the fasta file twice, rather than the fasta and gff3 file, so have corrected this and it is now running to Creating riboviz-style GFF3.

`system('Rscript --vanilla rscripts/create_files_for_riboviz.R -i ../example-datasets/fungi/histoplasma/annotation/Histoplasma_capsulatum_CDS.fasta -g ../example-datasets/fungi/histoplasma/annotation/Histoplasma_capsulatum_CDS.gff3 --out_dir . --out_cds histo.fasta --out_gff histo.gff3 -s ID -b 250 --remove_trailing "" --filter_seq type:CDS --exons_preordered')`

```
[1] "Creating riboviz-style GFF3..."
Error in stop_if_wrong_length("'seqnames'", ans_len) : 
  'seqnames' must have the length of the object to construct (1) or
  length 1
Calls: createRibovizGFF -> GRanges -> new_GRanges -> stop_if_wrong_length
Execution halted
[1] 1

```

**Comment by swinterbourne** [comment]
The data from Anita Sil's lab is available under the accession number [GSE68707](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE68707). The subseries which contains the ribosome profiling samples is available under the accession number [GSE68705](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE68705).

Of the samples 8 available in GSE68705 the 4 ribosome profiling samples of interest (excluding RNA-seq samples) are:
- [GSM1679356](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1679356) - Hyphae C footprint
- [GSM1679358](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1679358) - Hyphae D footprint
- [GSM1679360](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1679360) - Yeast C footprint
- [GSM1679362](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1679362) - Yeast D footprint

**Comment by 3mma-mack** [comment]
I've encountered a number of problems running the files through create_files_for_riboviz.R. The first being I was filtering for features of type CDS where in the file they listed as type cds, which was leading to the filtered temporary gff object being empty. Next the names of sequences in the fasta file are different from those used as seqnames, which is a problem, so I have changed the names in the fasta to match the seqnames in the gff, fortunately these are in the same order.

The next problem is the fasta file is made up of multiple contigs of small sizes, and the gff seems to list the ranges of coding sequences that I would expect from a genome. So I redownloaded files from [histo.ucsf.edu](http://histo.ucsf.edu/downloads/) specifically F_HCG217B.fasta.041130.gz as the fasta file, which I uncompressed and then copied into a fasta file, and ucsf_hc.01_1.G217B.gff3, as the page states 
'_Gene, exon, and CDS coordinates for G217B in GFFv3 format. Coordinates are relative to the GSC genome assembly above (F_HCG217B.fasta.041130.gz)_'. 

The names in the fasta did not match the names in the gff, due to extra information included in the column (ie "HISTO_AAM.Contig2 fasta.screen.ace from 81 to 23841") so I used` names(fasta) <- sapply(strsplit(names(fasta), ' '), "[[", 1)` to split the string where a space occurred and extract the first element. There were two occurrences where the result of this string was "HISTO_GX.Contig297\tfasta.screen.ace", so I used `names(fasta) <- sapply(strsplit(names(fasta), '\t'), "[[", 1)` to remove everything following the '\t' .

I compared the names in the fasta with the seqnames in the gff to double check that all the names matched. There were more unique sequences in the fasta than were present in the gff, so I filtered the fasta to include only the sequences listed in the gff using ` histo_fasta <- fasta[names(fasta) %in% gff_df$seqnames]`, then exported the file to be used in create_files_for_riboviz.R 

I ran the code step by step rather than using the console so I could check objects as errors occurred using the following arguments.

```
input <- 'rscripts/renamed_histo.fasta'
gff <- 'rscripts/histo.gff3'
output_dir <- "."
output_cds <- 'Histo.fasta'
output_gff <- 'Histo.gff3'
buffer <- 250
h5_file <-NULL
seq_id <- "ID"
codon_data_file <- NULL
num_cores <- 1
codons_exclude <- 0
remove_trailing <- "\\:"
filter_seq <- c("type:cds")
exons_preordered <- TRUE
```
This ran all the way through so I am going to check the files with check_fasta_gff to see if they are decent annotations

**Comment by 3mma-mack** [comment]
I ran dos2unix on the two files before I sent them to eddie to prevent any issues due to me creating the files on a windows systems and got the following output 

```
Metadata:
NumSequences    9580
NumFeatures     28740
NumCDSFeatures  9580

Issue summary:
Issue   Count
NoStopCodon     9580
IncompleteFeature       0
SequenceNotInGFF        0
NoIdName        0
SequenceNotInFASTA      0
DuplicateFeatureId      0
NoStartCodon    0
DuplicateFeatureIds     0
InternalStopCodon       0
MultipleCDS     0
```
Which is better than it was previously, as now the sequences are in the GFF, but we need to figure out why none of them have stop codons

**Comment by 3mma-mack** [comment]
I have redownloaded snapgene and had a look at the fasta file that apparently has no stop codons when checked with check_fasta_gff.
```
# Created by: RiboViz
# Date: 2021-08-11 11:36:52.123161
# Command-line tool: /exports/csce/eddie/biology/groups/wallace_rna/riboviz-emma/riboviz/riboviz/riboviz/tools/check_fasta_gff.py
# File: /exports/csce/eddie/biology/groups/wallace_rna/riboviz-emma/riboviz/riboviz/riboviz/check_fasta_gff.py
# Version: commit 816246e8c1aacdf5f8107f27bfc75e299d225406 date 2021-08-04 16:49:35+01:00
# fasta_file: Histo_29_07.fasta
# gff_file: Histo_29_07.gff3
# start_codons: ['ATG']
# NumSequences: 9580
# NumFeatures: 28740
# NumCDSFeatures: 9580
# NoStopCodon: 9580
# DuplicateFeatureId: 0
# SequenceNotInFASTA: 0
# NoIdName: 0
# MultipleCDS: 0
# SequenceNotInGFF: 0
# IncompleteFeature: 0
# DuplicateFeatureIds: 0
# InternalStopCodon: 0
# NoStartCodon: 0
```

All genes checked with snapgene has a start codon at positions 251-253, as expected from check_fasta_gff. These sequences also had a stop codon, though it was at postions -250 to -248 relative to the end of the transcript. This means when the file is checked the stop codon is counted as the first codon in the 3'UTR.

**Comment by 3mma-mack** [comment]
So after a bit of trial and error trying to change the input gff and fasta before running `create_files_for_riboviz.R`, I tried editing the output files. I increased the listed end and width of any feature with type CDS in the gff by 3nt, and added 3 Ns to the end of all the fasta sequences, so the 3UTR would still have a width of 250. 

After running `dos2unix` on the files (I initially forgot, which lead to lots of incomplete features being detected by `check_fasta_gff`),  `check_fasta_gff `only returned 9 issues out of 9580 CDSfeatures!

[features_issues_12_08_txt.txt](https://github.com/riboviz/example-datasets/files/6974021/features_issues_12_08_txt.txt)

So I am going to rename the gff and fasta files to something more descriptive and push them to 'add-new-species-HCapsulatum-91' and then our next step is to set up and test our first dataset.

**Comment by 3mma-mack** [comment]
When running git add on the fasta file the following warning was displayed:

```
$ git add Histoplasma_capsulatum_G217B_w_250utrs.fasta
warning: LF will be replaced by CRLF in fungi/histoplasma/annotation/Histoplasma_capsulatum_G217B_w_250utrs.fasta.
The file will have its original line endings in your working directory
```
I am worried that this may disrupt the changes made by dos2unix, so I will recheck the files using check_fasta_gff once they have been pushed.

Files have been renamed to Histoplasma_capsulatum_G217B_w_250utrs.fasta and Histoplasma_capsulatum_G217B_w_250utrs.gff3

**Comment by swinterbourne** [comment]
The methods section "Generation of ribosome footprint libraries" of the [paper](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005395) mentions using the "3′ linker ligation strategy" used in [Dunn et al ](https://elifesciences.org/articles/01179/figures#SD2-data) in addition to the libraries being multiplexed. There is no mention of the use of UMIs. 

From [supplementary file 2](https://elifesciences.org/download/aHR0cHM6Ly9jZG4uZWxpZmVzY2llbmNlcy5vcmcvYXJ0aWNsZXMvMDExNzkvZWxpZmUtMDExNzktc3VwcDItdjEueGxz/elife-01179-supp2-v1.xls?_hash=eSVHD1Jz2zaC3clPiZdM0DChH0d6ETT%2F7abNAg8fPK0%3D) in Dunn et al: 
"Linker-1 3' cloning adaptor for RNA fragments: appctgtaggcaccatcaat/3ddc"

**Comment by swinterbourne** [comment]
The config yaml file is available in the branch [add-new-species-HCapsulatum-91](https://github.com/riboviz/example-datasets/tree/add-new-species-HCapsulatum-91/fungi/histoplasma).

**Comment by swinterbourne** [comment]
I created a downsampled version of Hyphae C footprint (SRR2015208) (`head -n 400000 SRR2015208.fastq > subsample1.fastq`) and ran it through riboviz.

The `read_lengths.pdf` looks correct, it looks like the adapter has been removed correctly. The other output files look quite irregular:

[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/7014958/3nt_periodicity.pdf)
[pos_sp_rpf_norm_reads.pdf](https://github.com/riboviz/example-datasets/files/7014963/pos_sp_rpf_norm_reads.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/7014964/read_lengths.pdf)
[startcodon_ribogrid.pdf](https://github.com/riboviz/example-datasets/files/7014965/startcodon_ribogrid.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/7014967/startcodon_ribogridbar.pdf)

I will make another downsampled version with 1 000 000 reads to see if the output files improve.

**Comment by 3mma-mack** [comment]
A run of sample Hyphae_C, or SRR2015208, has successfully completed producing the following output files:

[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/7128390/read_lengths.pdf)
[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/7128391/3nt_periodicity.pdf)
[startcodon_ribogrid.pdf](https://github.com/riboviz/example-datasets/files/7128392/startcodon_ribogrid.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/7128396/startcodon_ribogridbar.pdf)
[pos_sp_rpf_norm_reads.pdf](https://github.com/riboviz/example-datasets/files/7128397/pos_sp_rpf_norm_reads.pdf)

Though a bit messy the 3nt_periodicity does have a peak at the start codon and there is some 3nt periodicity observable. The read lengths are as expected which is good. 

I believe this means that the config file is good and has the correct adapters, so I am going to test the rest of the samples as well.

**Comment by 3mma-mack** [comment]
So the run of all the samples has completed and the results look a little weird. Not 'something is very wrong' weird, just a little messy. @swinterbourne @FlicAnderson what do you think of the results? I wish Github supported the HTML file on issue tickets to make this easier but here are the pdf outputs for each sample. This was run just before the file name update in develop so the files still have the old names 

Hyphae_C

[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/7142592/3nt_periodicity.pdf)
[pos_sp_rpf_norm_reads.pdf](https://github.com/riboviz/example-datasets/files/7142593/pos_sp_rpf_norm_reads.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/7142594/read_lengths.pdf)
[startcodon_ribogrid.pdf](https://github.com/riboviz/example-datasets/files/7142595/startcodon_ribogrid.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/7142596/startcodon_ribogridbar.pdf)

Hyphae_D

[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/7142601/3nt_periodicity.pdf)
[pos_sp_rpf_norm_reads.pdf](https://github.com/riboviz/example-datasets/files/7142603/pos_sp_rpf_norm_reads.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/7142604/read_lengths.pdf)
[startcodon_ribogrid.pdf](https://github.com/riboviz/example-datasets/files/7142605/startcodon_ribogrid.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/7142606/startcodon_ribogridbar.pdf)

Yeast_C

[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/7142611/3nt_periodicity.pdf)
[pos_sp_rpf_norm_reads.pdf](https://github.com/riboviz/example-datasets/files/7142612/pos_sp_rpf_norm_reads.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/7142615/read_lengths.pdf)
[startcodon_ribogrid.pdf](https://github.com/riboviz/example-datasets/files/7142616/startcodon_ribogrid.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/7142618/startcodon_ribogridbar.pdf)

Yeast_D

[3nt_periodicity.pdf](https://github.com/riboviz/example-datasets/files/7142627/3nt_periodicity.pdf)
[pos_sp_rpf_norm_reads.pdf](https://github.com/riboviz/example-datasets/files/7142629/pos_sp_rpf_norm_reads.pdf)
[read_lengths.pdf](https://github.com/riboviz/example-datasets/files/7142632/read_lengths.pdf)
[startcodon_ribogrid.pdf](https://github.com/riboviz/example-datasets/files/7142633/startcodon_ribogrid.pdf)
[startcodon_ribogridbar.pdf](https://github.com/riboviz/example-datasets/files/7142634/startcodon_ribogridbar.pdf)


What I find strange is that both hyphae samples have 3 large peaks along the 5' end of the transcript, which is not seen in the yeast samples. Also the peak read lengths vary greatly, with the yeast samples having a large number of reads from 15 nt and a peak at 30 nt, Hyphae_C having a single, nice peak at 30 and Hyphae_D having a peak at 33 nt. Is it possible that different methods were used to extract reads from the Yeast and Hyphae samples? and is it possible that Hyphae_D uses a different sized adapter sequence?

**Comment by FlicAnderson** [comment]
Looking at this during hackathon (10Sept2021) discussion: 
* shows tight 3 nucleotide periodicity, but these strange features of the read length & some odd peaks, and the 2 strange 'artifacts overlaid' on the ribogrids (e.g vertical & diagonal on hyphae D for example).  @ewallace suspects it's possibly an issue in the data, rather than a riboviz issue. 

Q:  Are Hyphae C & D biological replicates, or different treatments? @swinterbourne will track this info down from the paper & update

**Comment by swinterbourne** [comment]
> Q: Are Hyphae C & D biological replicates, or different treatments? @swinterbourne will track this info down from the paper & update

I checked the paper: Hyphae C & D are biological replicates, Yeast C & D are also biological replicates.
