### ISSUE TITLE
Add new dataset for Homo sapien from Iwasaki et. al. Mol. Cell 2019

### ISSUE THREAD

**Issue by acope3** [riboviz/example-datasets#93]
See https://doi.org/10.1016/j.molcel.2018.11.026.

Thanks for starting to add a new dataset to example-datasets! This issue template includes the key steps, see [add-new-dataset.md](https://github.com/riboviz/example-datasets/add-new-dataset.md). Please edit as needed for your dataset.

- [x] Create a new branch of example-datasets with a helpful concise name, for example `cheng-entamoeba-123` if the dataset were generated by Dr. Cheng, from entamoeba, and the new issue ticket is number 123.
- [x] Identify paper or data source - list and link
- [x] Identify the species and strain used, check if example-datasets already has appropriate annotation and contaminant files.
- [x] (if new species) Find annotation data for the species and strain elsewhere.
- [x] (if new species *and* genus)  Create a genus folder in example-datasets.
- [x] (if new species) Download or create contaminants fasta file.
- [x] (if new species) Download or create transcriptome annotation fasta and gff files.
- [x] (if new species) Check annotation files for consistency with `check_fasta_gff`.
- [x] Identify the ribosome profiling samples from the dataset (some may be RNA-seq) - link database.
- [x] Identify adapter sequence - provide sequence.
- [x] Confirm or deny presence of UMIs and barcodes if used - describe if present.
- [x] If UMIs are present, create UMI regular expression.
- [x] Using information gathered, create config file.
- [x] Download sample data.
- [ ] (optional) Create downsampled data and fast test run on that.
- [x] Test run of full sized dataset.
- [x] Look at results - check for 3nt periodicity in coding regions, most common read lengths being 28-32 nt, and clear start and stop profiles.
- [x] Troubleshoot as necessary and discuss on issue ticket.
- [x] Update genus-level README.md and provenance section of config file.
- [x] Put in pull request to add to repository.

**Comment by acope3** [comment]
One thing I noticed is much of the code in `generate_stats_figs.R` assumes the CDS was created using a buffer as opposed to annotated UTRs. I've updated this as part of a local branch that I will push later after performing the regression tests. To give you an idea of how this impacts the results.

Here is what the position specific RPF normalized reads look like with the current code in the `develop` branch. 

[pos_sp_rpf_norm_reads-Iwasaki_etal_2019-develop_branch.pdf](https://github.com/riboviz/example-datasets/files/6893448/pos_sp_rpf_norm_reads-Iwasaki_etal_2019-develop_branch.pdf)

And here is what it looks like using my local code that takes the start and end of the CDS from the GFF3 file.

[pos_sp_rpf_norm_reads-Iwasaki_etal_2019-local_branch.pdf](https://github.com/riboviz/example-datasets/files/6893453/pos_sp_rpf_norm_reads-Iwasaki_etal_2019-local_branch.pdf)

**Comment by acope3** [comment]
See pull request #96

**Comment by FlicAnderson** [comment]
Dataset run, checked, config updated, merged to main, closing :) Great stuff @acope3!
